### ISSUE TITLE
take the last state of bi-lstm

### ISSUE THREAD

**Issue by weiyooooo** [weyoweyo/Kaggle#1]
lstm.py, line 220
comment: ht(batc，num_layers * num_directions, h, hidden_size) because of batch_first = True 
output = output[:, -1, :]
is meaningful only when bidirectional = False.

for bi-lstm, it should be 
 output =  output[:, -1, :] + l output[:, -2, :]

https://stackoverflow.com/questions/53010465/bidirectional-lstm-output-question-in-pytorch
https://stackoverflow.com/questions/50856936/taking-the-last-state-from-bilstm-bigru-in-pytorch

**Comment by weyoweyo** [comment]
code updated
